#!/system/bin/sh
set -x
insmod /system/lib/modules/app_monitor.ko
dir=/data/local/log/app_monitor
pidfile=/data/local/tmp/app_monitor.pid

if [ -f $pidfile ]; then
	pid=`cat $pidfile`
	if [ -d /proc/$pid -a "`cat /proc/$pid/comm 2>/dev/null`" == "`basename $0`" ]; then
		echo "Running with pid $pid"
	else
		echo "stale pid ($pid) found, removing"
		rm $pidfile
		pid=""
	fi
fi

function stop()  {
	rm $pidfile
	[ -n "$pid" ] && kill `ps | grep " $pid " | awk '{print $2}' | sort -r`
}

if [ "$1" == "stop" ]; then
	stop
	exit
elif [ "$1" == "restart" ]; then
	stop
	sleep 1
fi

if [ -f $pidfile ]; then
	pid=`cat $pidfile`
	if [ -d /proc/$pid -a "`cat /proc/$pid/comm`" == "`basename $0`" ]; then
		echo "script already running with pid $pid"
		exit 1;
	else
		echo "stale pid ($pid) found, removing"
		rm $pidfile
	fi
	pid=""
fi

renice 19 $$

mkdir -p $dir
(

#TODO...
#TS=`date +"%Y%m%d%H%"`
#cnt=`ls $dir/app_monitor.${TS}* | wc -l`
#if [ "0$cnt" -gt 0 ]; then
#	TS="${TS}.$((cnt+1))"
#fi

echo 2000 > /sys/module/app_monitor/parameters/row_limit
echo $((10*60)) > /sys/module/app_monitor/parameters/time_limit_sec

while [ -f $pidfile ];
do
	if [ ! -f /proc/app_monitor_raw ];
	then
		sleep 10
		continue
	fi
	TS=`date +"%Y%m%d%H%M%S"`
	dd if=/proc/app_monitor_raw bs=4096 | gzip -1 > $dir/app_monitor.${TS}.gz
done
)&

echo $! > $pidfile
